### ISSUE TITLE
clean up functions + build package

### ISSUE THREAD

**Issue by nehamoopen** [Fesch-star/cognitivemapr#12]
- [x] move redundant and broken functions out of the R folder
- [x] update functions to use `package::function` convention
- [x] add some initial documentation to all functions, also linked to #4 
- [x] attempt to build package

**Comment by jelletreep** [comment]
fixed some of these open issues :)

**Comment by jelletreep** [comment]
Based on error messages I updated some functions to package::function, but it might not cover all functions yet
